apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name:  {{ include "location-service.fullname" . }}-ingress-requestrouting
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/enable-cors: "false"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /api/requestrouting/location/$1
spec:
  tls:
  - secretName: ingress.local.tls
    hosts:
      - '*.local'
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - path: /location/api/requestrouting/location/?(.*)
        backend:
          serviceName:  {{ include "location-service.fullname" . }}
          servicePort: 80
  - host: {{ .Values.hostname_trafficmanager }}
    http:
      paths:
      - path: /location/api/requestrouting/location/?(.*)
        backend:
          serviceName:  {{ include "location-service.fullname" . }}
          servicePort: 80

