# Default values for license-accountant.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: pltnonprodacr.azurecr.io/license-accountant
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

hostname: "unknown-from-helm-values"
appName: "unknown-from-helm-values"
hostname_trafficmanager: "unknown-from-helm-values"
devhosts_alias: "127.0.0.1"
devhosts_alias_hostNames: "unknown-from-helm-values.host.docker.internal"

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  paths: []
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
  swagger:
    enabled: false

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

azureKeyVault:
  url: "unknown-from-helm-values"
  clientId: "unknown-from-helm-values"
  clientSecret: "unknown-from-helm-values"

CORECLR_ENABLE_PROFILING: "0"
CORECLR_NEWRELIC_HOME: "/usr/local/newrelic-netcore20-agent"
CORECLR_PROFILER: '{36032161-FFC0-4B61-B559-F6C5D41BAE5A}'
CORECLR_PROFILER_PATH: "/usr/local/newrelic-netcore20-agent/libNewRelicProfiler.so"
NEW_RELIC_LICENSE_KEY: 'eu01xxdc9ba9b696da417d0db367ee673bfdNRAL'
