apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "identity-service.name" . }}-web
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/enable-cors: "false"
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-buffers: "8 256k"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    helm.sh/chart: {{ include "identity-service.chart" . }}
    app.kubernetes.io/name: {{ include "identity-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  tls:
  - secretName: ingress.local.tls
    hosts:
      - '*.local'
  rules:
    - host: {{ .Values.hostname }}
      http:
        paths: 
          - path: /identity_/web/?(.*)
            backend:
              serviceName: {{ include "identity-service.name" . }}-web
              servicePort: 80
    - host: {{ .Values.hostname_trafficmanager }}
      http:
        paths:
          - path: /identity_/web/?(.*)
            backend:
              serviceName: {{ include "identity-service.name" . }}-web
              servicePort: 80
