apiVersion: v1
kind: Service
metadata:
  name: {{ include "identity-service.name" . }}-api
  labels:
    app.kubernetes.io/name: {{ include "identity-service.name" . }}-api
    helm.sh/chart: {{ include "identity-service.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.api.type }}
  ports:
    - name: http
      port: {{ .Values.service.api.port }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "identity-service.name" . }}-api
    app.kubernetes.io/instance: {{ .Release.Name }}