apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name:  {{ include "organization-management-service.fullname" . }}-ingress-organization
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/enable-cors: "false"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - path: /organization/?(.*)
        backend:
          serviceName:  {{ include "organization-management-service.fullname" . }}
          servicePort: 80
  - host: {{ .Values.hostname_trafficmanager }}
    http:
      paths:
      - path: /organization/?(.*)
        backend:
          serviceName:  {{ include "organization-management-service.fullname" . }}
          servicePort: 80